### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': The provided selector is empty.

### ISSUE THREAD

**Issue by WebmakersJaap** [appleple/modal-video#7]
Apparently you can't use jQuery's version of ModalVideo in a "$(this)" context.
The followin code won't work:

`<a class="js-modal-btn youtube" data-video-id="e_oD9LCszd0">Youtube link</a>
<a class="js-modal-btn vimeo" data-video-id="36862440">Vimeo link</a>`

`$(".js-modal-btn").each(function() {
	var channel = ($(this).hasClass('vimeo') ? 'vimeo' : 'youtube'); 
	$(this).modalVideo({'channel': channel});
});`

**Comment by steelydylan** [comment]
Hi @WebmakersJaap 

Thank you for letting me know about this
yeah actually this modal-video uses jquery as just an interface to execute VanilaJS
sorry about that

I'll fix the problem soon so that you can use 'this' context as well
and I'll also add option data-channel so as not to write such code anymore ;)

**Comment by steelydylan** [comment]
Hi @WebmakersJaap 

I just added 'data-channel' option so you don't have to run $.fn.modalVideo separetely.
just run $('.js-modal-btn').modalVideo();
and write html as following

`
<a class="js-modal-btn youtube" data-video-id="e_oD9LCszd0">Youtube link</a> <a class="js-modal-btn" data-video-id="36862440" data-channel="vimeo">Vimeo link</a>
`
